import axios from 'axios';
import AnimeCard from 'components/AnimeCard';
import DogCard from 'components/DogCard';
import Feed from 'components/Feed';
import Head from 'next/head';
import Image from 'next/image';
import {useState, useEffect, useRef} from 'react';

export default function Home() {

  const [activeTab, setActiveTab] = useState('anime');
  const [anime, setAnime] = useState([]);
  const [dogFacts, setDogFacts] = useState([]);
  const dogRef = useRef(null);
  const animeRef = useRef(null)


 

  useEffect(() => {
   
    
   
 
    const intervalId = setInterval(getDogs, Math.random() * 1500);

    return () => clearInterval(intervalId);
  }, []);

  useEffect(() => {
   
    
   

    const intervalId = setInterval(getAnime, Math.random() * 1500);

    return () => clearInterval(intervalId);
  }, []);


  const getDogs = async() =>{

    try{
      const res = await axios.get("https://dog-api.kinduff.com/api/facts")
      const fact = res.data.facts
      setDogFacts(prevFacts => [...prevFacts, fact]);
 
      
    } catch(err){

      console.log(err)
    }
    
    
  }

  const getAnime = async ()=>{

    try{
      const res = await axios.get("https://animechan.vercel.app/api/random")

      const data = res.data
      setAnime(prevAnime => [...prevAnime, data])
    } catch(err){

      console.log(err)
    }
  }






  

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className='page-layout'>
          <div className='sidebar'>
            <button onClick={() => setActiveTab('anime')} className='btn-primary'>Anime</button>
            <button onClick={() => setActiveTab('dogs')} className='btn-primary'>Dogs</button>
          </div>
          <div >
         


            {activeTab === 'anime'
          ? <Feed currentTab={activeTab} feedData={anime}/>
          : <Feed currentTab={activeTab} feedData={dogFacts}/>}



          
          </div>

        </div>
      </main>
    </>
  )
}


